package corenlp

import (
	"encoding/json"
	"io/ioutil"

	"github.com/nongdenchet/go-corenlp/connector"
	"github.com/nongdenchet/go-corenlp/document"
)

// Annotate annotate the text using a connector provided.
func Annotate(p connector.Connector, text string) (root *document.Document, err error) {
	response, err := p.Run(text)
	if err != nil {
		return nil, err
	}
	defer response.Close()

	rawjson, err := ioutil.ReadAll(response)
	if err != nil {
		return nil, err
	}
	return ParseOutput(rawjson)
}

// ParseOutput parse a json output generated by Stanford CoreNLP.
func ParseOutput(rawjson []byte) (root *document.Document, err error) {
	err = json.Unmarshal(rawjson, &root)
	return root, err
}
